spring.application.name=gewa
# H2 Configuration (Commented out)
# spring.datasource.url=jdbc:h2:mem:gewa
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true

# MySQL Configuration
# MySQL Configuration (Using Environment Variables for Security)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true 
# this line tells spring to wait and let hibernate create the tables first and then run the data.sql file
